language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install -r flaskcli_pkg/templates/dev/requirements.txt
# command to run tests
script:
  - python3 flaskcli_pkg/main.py || python flaskcli_pkg/main.py
